### ISSUE TITLE
Ethereum

### ISSUE THREAD

**Issue by shmishleniy** [flyingw/umbrella#5]
parity-ethereum looks too big and complicated to copy it directly to the project.
Also it's fully designed to start as node instance so seems a lot can be removed.
I'll fork it to remove all the unused first.
@doxtop @tellnobody1

**Comment by doxtop** [comment]
посмотри tcp цикл в мейне. там нужен только набор команд для хендшейка и сами меседжи 2или 3

**Comment by shmishleniy** [comment]
https://github.com/ethereum/devp2p/blob/master/rlpx.md#network-formation

**Comment by shmishleniy** [comment]
https://github.com/ethereum/devp2p/blob/master/caps/eth.md
